import {
    sql,
    blender,
    canva,
    threejs,
    arduino,
    python,
    tensorflow,
    bootstrap,
    contact,
    api,
    java,
    django,
    flask,
    css,
    git,
    github,
    html,
    javascript,
    linkedin,
    mongodb,
    react,
    sass,
    pytorch,
    opencv,
    langchain,
} from "../assets/icons";

import {
    boat,
    durga,
    gainnFintechIcon,
    hobbyTribeIcon,
    krishna,
    lady,
    lotus,
    projectCell,
    techxleIcon,
    wave,
} from "../assets/images";

export const skillLevelColors = {
    Expert: { bg: "#10B981", text: "#FFFFFF", border: "#059669" },       
    Advanced: { bg: "#3B82F6", text: "#FFFFFF", border: "#2563EB" },
    Intermediate: { bg: "#94A3B8", text: "#FFFFFF", border: "#64748B" },
};

export const skills = [
    // --- 🧠 AI, MACHINE LEARNING & GEN AI ---
    { name: "LangGraph", type: "AI/ML", level: "Expert" },
    { name: "Large Language Models (LLMs)", type: "AI/ML", level: "Expert" },
    { name: "Agentic AI Systems", type: "AI/ML", level: "Advanced" },
    { name: "Generative AI", type: "AI/ML", level: "Expert" },
    { name: "Prompt Engineering", type: "AI/ML", level: "Advanced" },
    { name: "LLM Evaluation & Testing", type: "AI/ML", level: "Advanced" },
    { name: "Anthropic Claude API", type: "AI/ML", level: "Advanced" },
    { name: "Groq", type: "AI/ML", level: "Intermediate" },
    { name: "LangSmith", type: "AI/ML", level: "Advanced" },
    { name: "RAG", type: "AI/ML", level: "Expert" },
    { name: "MediaPipe", type: "AI/ML", level: "Expert" },
    { name: "PyTorch", type: "AI/ML", level: "Advanced" },
    { name: "TensorFlow", type: "AI/ML", level: "Advanced" },
    { name: "OpenCV", type: "AI/ML", level: "Advanced" },
    { name: "Scikit-learn", type: "AI/ML", level: "Advanced" },
    { name: "Vision Transformers (ViT)", type: "AI/ML", level: "Advanced" },
    { name: "LSTMs & Time-Series", type: "AI/ML", level: "Advanced" },
    { name: "Multi-modal Learning", type: "AI/ML", level: "Advanced" },
    { name: "OCR", type: "AI/ML", level: "Advanced" },
    { name: "Natural Language Processing (NLP)", type: "AI/ML", level: "Expert" },
    { name: "CNNs", type: "AI/ML", level: "Advanced" },
    { name: "Sentiment Analysis", type: "AI/ML", level: "Advanced" },

    // --- 💻 SDE & SYSTEMS ---
    { name: "System Design", type: "SDE", level: "Advanced" },
    { name: "Data Structures & Algorithms", type: "SDE", level: "Advanced" },
    { name: "Distributed Training", type: "SDE", level: "Advanced" },
    { name: "OOP", type: "SDE", level: "Advanced" },
    { name: "CI/CD", type: "SDE", level: "Advanced" },
    { name: "Automated Testing (pytest)", type: "SDE", level: "Advanced" },
    { name: "RocksDB", type: "SDE", level: "Intermediate" },
    { name: "RESTful APIs", type: "SDE", level: "Advanced" },
    { name: "DBMS", type: "SDE", level: "Advanced" },

    // --- 🛠️ LANGUAGES & BACKEND ---
    { name: "Python", type: "Backend", level: "Expert" },
    { name: "Django", type: "Backend", level: "Advanced" },
    { name: "FastAPI", type: "Backend", level: "Advanced" },
    { name: "Streamlit", type: "Backend", level: "Advanced" },
    { name: "Java", type: "Backend", level: "Advanced" },
    { name: "C++", type: "Backend", level: "Advanced" },
    { name: "SQL (MySQL)", type: "Backend", level: "Advanced" },
    { name: "PostgreSQL", type: "Backend", level: "Advanced" },
    { name: "Celery", type: "Backend", level: "Advanced" },
    { name: "Flask", type: "Backend", level: "Intermediate" },
    { name: "Redis", type: "Backend", level: "Intermediate" },

    // --- ☁️ CLOUD & TOOLS ---
    { name: "Azure AI Search", type: "Cloud", level: "Expert" },
    { name: "AWS S3", type: "Cloud", level: "Advanced" },
    { name: "Docker", type: "Cloud", level: "Advanced" },
    { name: "Git & GitHub", type: "Cloud", level: "Advanced" },
    { name: "MongoDB", type: "Cloud", level: "Intermediate" },
    { name: "PowerApps", type: "Cloud", level: "Intermediate" },

    // --- 🎨 FRONTEND & DESIGN ---
    { name: "ReactJS", type: "Frontend", level: "Advanced" },
    { name: "Angular", type: "Frontend", level: "Intermediate" },
    { name: "Three.JS", type: "Frontend", level: "Intermediate" },
    { name: "HTML5/CSS3", type: "Frontend", level: "Advanced" },
    { name: "JavaScript (ES6+)", type: "Frontend", level: "Advanced" },
    { name: "Bootstrap / Sass", type: "Frontend", level: "Intermediate" },
    { name: "Blender", type: "Design", level: "Intermediate" },
    { name: "Canva", type: "Design", level: "Intermediate" },

    // --- 🤖 ROBOTICS ---
    { name: "Arduino", type: "Robotics", level: "Advanced" },
    { name: "Proteus", type: "Robotics", level: "Intermediate" },
];

export const experiences = [
    {
        title: "Artificial Intelligence Intern",
        company_name: "TechXL LLC",
        location: "Remote",
        icon: techxleIcon,
        iconBg: "#6366F1",
        date: "June 2026 – Present",
        type: "work",
        points: [
            "Agentic AI Systems: Designed and shipped a tool-calling AI agent for autonomous board-health monitoring, enforcing evidence-gating and usage limits that reject unsupported model recommendations before they reach a human reviewer.",
            "LLM Infrastructure: Built a provider-agnostic LLM integration layer (Anthropic, Groq) with automatic retry and failover, and a pluggable board-integration layer unifying four project-tracker APIs (Linear, Azure DevOps, GitHub Issues, and an internal option).",
            "Reliability Engineering: Resolved state-management race conditions and data-consistency bugs; wrote automated agent evaluation tests and implemented end-to-end audit logging for deterministic CI and production monitoring.",
        ],
    },
    {
        title: "Research Assistant",
        company_name: "University of California, Irvine",
        location: "Irvine, CA",
        icon: "🔬",
        iconBg: "#8B5CF6",
        date: "May 2026 – Present",
        type: "work",
        points: [
            "Model Optimization: Improved a PyTorch 3D pose-discriminator's test accuracy from 89% to 95%+ by diagnosing a BatchNorm training instability and re-tuning the learning-rate schedule.",
            "Failure Mode Analysis: Identified and closed a spurious accuracy shortcut in the pose classifier through redesigned sample pairing and hard-negative sampling.",
            "Evaluation Infrastructure: Built a classification evaluation suite and synthetic-noise augmentation pipeline for reproducible offline validation across 15+ 3D human pose datasets, supporting a literature review targeting academic submission.",
        ],
    },
    {
        title: "Masters in Computer Science",
        company_name: "University of California, Irvine",
        location: "Irvine, CA",
        icon: "🎓",
        iconBg: "#3B82F6",
        date: "September 2025 – Present",
        type: "education",
        points: [
            "Graduate studies in Computer Science with focus on AI/ML systems",
            "Advanced coursework in machine learning, distributed systems, and software engineering",
            "Research in production AI systems deployment",
        ],
    },
    {
        title: "Associate AI Engineer",
        company_name: "Techxle",
        location: "Mumbai (Remote)",
        icon: techxleIcon,
        iconBg: "black",
        date: "August 2024 – August 2025",
        type: "work",
        points: [
            "GenAI Document Pipelines: Architected production-grade RAG pipelines using LangGraph and LangSmith to transform unstructured insurance binders into structured JSON, delivering a client-ready solution for Lockton and TRNDigital in 2 weeks and cutting processing time from hours to seconds.",
            "Intelligent Talent Acquisition: Engineered a resume-screening engine using Azure AI Search and GPT-based re-ranking, improving candidate-to-role matching precision and reducing manual HR screening effort by 80%.",
            "Technical Leadership: Mentored 2 interns through structured NLP and Computer Vision roadmaps, increasing sprint velocity and enabling independent delivery of production-ready features.",
        ],
    },
    {
        title: "AI & DS Intern",
        company_name: "The Hobby Tribe",
        location: "Mumbai",
        icon: hobbyTribeIcon,
        iconBg: "#FFA500",
        date: "June 2023 – August 2023",
        type: "work",
        points: [
            "Department Foundation: Founded the AI department as its first hire, defining the technical roadmap for automated hobby-skill assessment.",
            "Automated Evaluation: Built CNN-based image comparison and NLP grading models, automating 60% of manual assessment tasks and reducing instructor workload.",
            "Scalable Personalization: Deployed automated feedback pipelines that increased student engagement through data-driven, self-paced learning paths.",
        ],
    },
    {
        title: "AI & ML Intern",
        company_name: "Gainn Fintech",
        location: "Mumbai",
        icon: gainnFintechIcon,
        iconBg: "#62cff4",
        date: "January 2023 – April 2023",
        type: "work",
        points: [
            "Predictive Analytics: Built a Bidirectional LSTM forecasting system achieving 73% directional accuracy in stock-movement prediction.",
            "Data Pipeline Optimization: Engineered real-time pipelines fusing sentiment analysis with time-series data to improve investment decision-making.",
            "Risk Mitigation: Surfaced automated market signals that helped reduce portfolio risk through proactive alerts.",
        ],
    },
    {
        title: "B.E. in AI & Data Science",
        company_name: "Father Agnel College of Engineering",
        location: "Mumbai",
        icon: "🎓",
        iconBg: "#3B82F6",
        date: "January 2020 – August 2024",
        type: "education",
        points: [
            "Bachelor's degree with Computer Vision patent achievement",
            "Graduated with distinction in AI & Data Science",
            "Secured national patent for computer vision innovation in medical imaging diagnostics",
        ],
    },
    {
        title: "Technical Team Member",
        company_name: "Project Cell CRCE",
        icon: projectCell,
        iconBg: "#00979C",
        date: "June 2021 – December 2021",
        type: "work",
        points: [
            "Autonomous Robotics: Designed and built Arduino-based robots using sensor fusion and real-time navigation algorithms to operate in complex environments without human input.",
            "National Competition: Competed in IIT Bombay's e-Yantra Robotics Competition (EYRC), gaining hands-on experience in hardware-software integration and embedded systems.",
            "Foundation of Expertise: Built the problem-solving and embedded-systems skills that later shaped my work in Computer Vision and AI.",
        ],
    },
    {
        title: "Shree Arihant Krupa Foundation",
        company_name: "Non-Profit Organization",
        location: "Mumbai",
        icon: "❤️",
        iconBg: "#F59E0B",
        date: "January 2020 – Present",
        type: "ngo",
        points: [
            "Grew up in an environment that taught me to put others before me",
            "Healthcare Infrastructure: Beyond meal drives, we provide critical medical equipment to hospitals and directly fund life-saving procedures for families in financial distress",
            "Educational Equity: We provide comprehensive financial aid for children's tuition and supplies, ensuring that financial barriers do not prevent access to schooling",
            "Animal Welfare: Actively engaged in animal safety and providing professional veterinary services to strays and local shelters",
            "Elderly Care: Supporting senior citizens with home-cooked meals, companionship, and essential care services",
            "Infrastructure Impact: Built 3 orphanages with educational facilities, established 5 Digital Centers in rural Zillas with 100+ computers, distributed 500+ cycles, 1000+ uniforms, and 2000+ books to underprivileged students",
            "Philosophy: Emphasizing Jeevdaya (compassion for all living beings) and Anukampa (empathy) as core life principles",
        ],
    },
];

export const socialLinks = [
    {
        name: 'Contact',
        iconUrl: contact,
        link: '/contact',
    },
    {
        name: 'GitHub',
        iconUrl: github,
        link: 'https://github.com/pysac17',
    },
    {
        name: 'LinkedIn',
        iconUrl: linkedin,
        link: 'https://www.linkedin.com/in/sachijshah/',
    }
];

export const projects = [
    {
        name: 'Hierarchical 3D Reconstruction Pipeline (UCI)',
        problem: 'Reconstructing 3D scenes from noisy, unstructured real-world images.',
        tech: ['DINOv2', 'HDBSCAN', 'ALIKED', 'LightGlue'],
        impact: ['Achieved an 87% registration rate by automating semantic clustering and geometric matching', 'Overcame challenges with repetitive structures'],
        githubLink: 'https://github.com/pysac17/273P-project',
        liveLink: '#',
        hasPatent: false,
    },
    {
        name: 'Brainwave-Based Adaptive Learning (UCI)',
        problem: 'Standard learning platforms don\'t adapt to user cognitive fatigue or mental load.',
        tech: ['Django', 'Celery', 'BLE', 'Scikit-learn'],
        impact: ['Achieved 98% accuracy in real-time cognitive state detection (focus vs. neutral) with sub-200ms inference', 'Generated personalized study plans that maximized "deep work" duration'],
        githubLink: 'https://github.com/areebar-netizen/MCS_Capstone',
        liveLink: '#',
        hasPatent: false,
    },
    {
        name: 'High-Concurrency Transaction Engine (UCI)',
        problem: 'Benchmarking performance trade-offs between OCC and 2PL in high-contention environments.',
        tech: ['RocksDB', 'C++', 'Multi-threading'],
        impact: ['Engineered a high-performance layer to handle shared-key workloads', 'Optimized critical system bottlenecks to maintain predictable latency under high thread contention'],
        githubLink: 'https://github.com/pysac17/223P-project',
        liveLink: '#',
        hasPatent: false,
    },
    {
        name: 'Deep RL for Autonomous Racing (UCI)',
        problem: 'Mastering high-speed maneuvering and sharp turns in simulated autonomous driving.',
        tech: ['PyTorch', 'Reinforcement Learning (PPO/DQN)', 'Custom Telemetry'],
        impact: ['Developed a custom reward architecture that balanced speed with smooth steering', 'Resulted in a model capable of completing full-lap cycles on complex circuits'],
        githubLink: 'https://github.com/pysac17/aiProject',
        liveLink: '#',
        hasPatent: false,
    },
    {
        name: 'Live Yoga Posture Detection (Patent Holder)',
        problem: 'Low-angle poses (like planks) often cause computer vision systems to fail.',
        tech: ['MediaPipe', 'CNNs', 'Python'],
        impact: ['Resolved critical detection failures to achieve 100% reliability across standard routines', 'Secured a National Patent (No. 202321077089) for the methodology'],
        githubLink: 'https://github.com/pysac17/YogaGuru',
        liveLink: '#',
        hasPatent: true,
    },
    {
        name: 'Satellite Contrail Detection',
        problem: 'Environmental monitoring through satellite imagery analysis.',
        tech: ['MaxViT', 'EfficientNet', 'PyTorch'],
        impact: ['Identified a 3% accuracy improvement for environmental monitoring', 'Benchmarked multiple architectures via grid-search hyperparameter tuning'],
        githubLink: 'https://github.com/pysac17/contrails-detection',
        liveLink: '#',
        hasPatent: false,
    },
    {
        name: 'Unscript Hackathon (Runner Up)',
        problem: 'High-volume document processing and quality classification.',
        tech: ['OCR', 'Image Processing', 'Python'],
        impact: ['Built OCR-based image quality classifier and extraction tool', 'Secured runner-up at Unscript AIML Hackathon 2023'],
        githubLink: 'https://github.com/GlenR16/CtrlAlt-Elite_Unscript-2k23',
        liveLink: '#',
        hasPatent: false,
    },
    {
        name: 'NASA Data Display',
        problem: 'Making complex space weather data comprehensible to the public.',
        tech: ['Blender', '3D Visualization', 'Data Processing'],
        impact: ['Created interactive 3D tool for solar probe data visualization', 'Made space weather data accessible for public understanding'],
        githubLink: 'https://github.com/khushi-14/luminary_nasaspaceappschallange',
        liveLink: '#',
        hasPatent: false,
    },
    {
        name: 'Netflix Clone',
        problem: 'Building a modern streaming interface with real API integration.',
        tech: ['ReactJS', 'TMDB API', 'Responsive Design'],
        impact: ['Fully functional streaming UI with dynamic movie listings', 'Implemented search and responsive design features'],
        githubLink: '#',
        liveLink: 'https://netflix-clone-beta-one-84.vercel.app/',
        hasPatent: false,
    },
    {
        name: 'Attendance & Extracurricular Tracker',
        problem: 'Comprehensive school management for multiple stakeholders.',
        tech: ['Django', 'Full-stack Development', 'Database Design'],
        impact: ['Built management app for teachers, students, and parents', 'Enabled tracking of academic reports and extracurricular activities'],
        githubLink: 'https://github.com/pysac17/codeDiggers/',
        liveLink: '#',
        hasPatent: false,
    },
    {
        name: 'Inventory Management System',
        problem: 'Real-time inventory and sales tracking for businesses.',
        tech: ['Full-stack Development', 'Real-time Dashboards', 'Database Systems'],
        impact: ['Developed tracking system for restaurants and retail stores', 'Provided instant visibility into stock and revenue'],
        githubLink: 'https://github.com/Elvis-Dodti/pos_mms',
        liveLink: '#',
        hasPatent: false,
    },
    {
        name: 'Autonomous Line Following Robot',
        problem: 'Autonomous navigation using sensor fusion and real-time algorithms.',
        tech: ['Arduino', 'Sensor Fusion', 'Real-time Navigation'],
        impact: ['Successfully navigated straight lines, zigzags, and circular paths', 'Competed in IIT Bombay\'s e-Yantra Robotics Competition'],
        githubLink: 'https://github.com/pysac17/arduino-projects',
        liveLink: '#',
        hasPatent: false,
    },
    {
        name: 'Obstacle Detection & Avoidance Robot',
        problem: 'Real-time obstacle detection and navigation for autonomous robots.',
        tech: ['Arduino', 'Proximity Sensors', 'Decision Logic'],
        impact: ['Built real-time obstacle detection and navigation system', 'Demonstrated sensor integration and real-time decision making'],
        githubLink: 'https://github.com/pysac17/arduino-projects',
        liveLink: '#',
        hasPatent: false,
    },
];

// Export available art images for the ArtGallery component
export const artImages = {
    boat,
    durga,
    krishna,
    lady,
    lotus,
    wave,
};